### ISSUE TITLE
Animation not running and getting warning instead

### ISSUE THREAD

**Issue by enter802** [winstxnhdw/KinematicBicycleModel#4]
When I try to run the animation, I am getting the following warning message that halts the animation:

`UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you have outputted the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(`

So I assigned the variable `anim` for function `FuncAnimation` and uncommented `anim.save('animation.gif', writer='imagemagick', fps=50)`. With this change, I see the a full white plot screen and the following on the console:

![image](https://user-images.githubusercontent.com/9440833/153077251-851def64-40b0-4705-8ed8-35325b0cf1b3.png)

Not sure what is it that I need to do to remedy this. Your help will be highly appreciated. Thanks in advance.

**Comment by winstxnhdw** [comment]
Don't uncomment `anim.save()` if you want to see the animation immediately. The `save()` method will run through the entire animation before showing the plot. Not very sure why you are receiving a warning. Make sure you have pulled the latest clone from the repository and that your version of matplotlib is >= 3.4.0

**Comment by enter802** [comment]
> Don't uncomment `anim.save()` if you want to see the animation immediately. The `save()` method will run through the entire animation before showing the plot. Not very sure why you are receiving a warning. Make sure you have pulled the latest clone from the repository and that your version of matplotlib is >= 3.4.0

I pulled the latest one and my matplotlib version is 3.5.0

**Comment by winstxnhdw** [comment]
@enter802 I just tested it on Arch, Ubuntu and Windows on both matplotlib 3.5.0 and 3.4.0. It's working on all of them. You may want to try reinstalling matplotlib. You might have some package conflict/corruption. You can try running it again in a virtual or conda environment.

**Comment by enter802** [comment]
@winstxnhdw it still does not work. I have played with an example that uses the animation function and it seems to be working. So I guess nothing wrong with `matplotlib` after all.

**Comment by winstxnhdw** [comment]
@enter802 Sorry, I am not sure how I can help you fix this. If you'd like, you can try a similar animation I made [here](https://github.com/winstxnhdw/FullStanleyController).

**Comment by enter802** [comment]
> @enter802 Sorry, I am not sure how I can help you fix this. If you'd like, you can try a similar animation I made [here](https://github.com/winstxnhdw/FullStanleyController).

Thanks a lot. Really appreciate it!
