### ISSUE TITLE
not subscriptable

### ISSUE THREAD

**Issue by myildirimm** [winstxnhdw/KinematicBicycleModel#5]
File "animate.py", line 9, in <module>
    from libs.car_description import Description
  KinematicBicycleModel-main\libs\car_description.py", line 5, in <module>
    class Description:
  KinematicBicycleModel-main\libs\car_description.py", line 80, in Description
    def plot_car(self, x: float, y: float, yaw: float, steer: float) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
TypeError: 'type' object is not subscriptable

**Comment by myildirimm** [comment]
I have got the above error when trying to run animate.py.

**Comment by winstxnhdw** [comment]
You must be on Python 3.10 or greater.

**Comment by myildirimm** [comment]
Thanks, look like Python 3.10 has not arrived in Anaconda yet. Will try later on.

**Comment by myildirimm** [comment]
conda create --name py310 python=3.10
Solved and animation works well.
Scipy is needed aswell for requirements.
