### ISSUE TITLE
The meaning of normalise_angle

### ISSUE THREAD

**Issue by olixu** [winstxnhdw/KinematicBicycleModel#6]
Hi, thanks for your meaningful works.

What is the meaning of:

```python
normalise_angle = lambda angle : atan2(sin(angle), cos(angle))
```

**Comment by winstxnhdw** [comment]
Hi @olixu, excellent question.

The function normalises any angle between -pi and pi. You can see an illustration I made on Desmos [here](https://www.desmos.com/calculator/zljact3ayq).

**Comment by olixu** [comment]
> 

Thanks!
